# Generated by Django 3.1.1 on 2021-02-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0001_initial'),
        ('accounts', '0002_auto_20210207_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(to='Receptionist.Category'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='degree',
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.ManyToManyField(to='Receptionist.Degree'),
        ),
    ]
