# Generated by Django 2.2.5 on 2021-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(blank=True, max_length=15, null=True)),
                ('TrxID', models.CharField(blank=True, max_length=35, null=True)),
                ('amount', models.FloatField(blank=True, max_length=10, null=True)),
                ('is_apply', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accept', 'Accept')], default='Pending', max_length=7, null=True)),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('prescribe', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
