# Generated by Django 3.1.1 on 2021-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_remove_appointment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
