# Generated by Django 3.1.1 on 2021-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_appointment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='TrxID',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_apply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
