# Generated by Django 3.1.1 on 2021-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20210208_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accept', 'Accept')], default='Pending', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
