# Generated by Django 3.1.1 on 2021-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20210208_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescribe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
